### PR TITLE
Keras 2 to 3 migration

### PR DESCRIPTION
**Pull request by kayla-leonard**
Had to temporarily disable multi-gpu support... will add back later on

### CODE REVIEW

**Comment by gmwendel** [comment]
Committed some minor changes for the updated dependencies.  

https://github.com/gmwendel/PLSE/blob/de7d9ca43e9862ce95e7c8ea1afd38435c0eca92/plse/traincounter.py#L43 should have the comment removed from the extra zeros.

https://github.com/gmwendel/PLSE/blob/de7d9ca43e9862ce95e7c8ea1afd38435c0eca92/plse/traincounter.py#L47 may have issues saving the network if you specify a directory that does not exist maybe something like the following could be added, although it is probably better to do this check before training the network.

```
import os
from pathlib import Path

def save_model(plse_counter, network_output, filename="model.keras", overwrite=False):
    # Ensure the directory exists
    Path(network_output).mkdir(parents=True, exist_ok=True)

    # Construct the full file path
    file_path = os.path.join(network_output, filename)

    # Check if the file already exists
    if os.path.exists(file_path) and not overwrite:
        print(f"Error: {file_path} already exists. Use 'overwrite=True' to overwrite it.")
        return

    # Save the model
    plse_counter.save(file_path)
    print(f"Model saved to {file_path}")

# Example usage
network_output = "network_output"
plse_counter.save_model(plse_counter, network_output, overwrite=False)
```

It would be very useful to have the model also be [exported as a tf model](https://keras.io/api/models/model_saving_apis/export/) after training is complete.

The 'test' code is also broken with these updates, but it might be worth rethinking how this is done as it uses a pre-trained network and requires dragging waveform files through the git history which is quite inefficient...

**Comment by kayla-leonard** [comment]
I'm still using python 3.9 since that's what was there at the time

**Comment by gmwendel** [comment]
Sounds good, the setup script is updated to reflect compatibility with python 3.9.  Let me know if you see anything missing in the install instructions otherwise I think it is ready to merge.

**Comment by gmwendel** [comment]
Also, you should add your name to the author section in setup.py, it should be fine to just include it in this PR.

**Comment by kayla-leonard** [comment]
fine to merge from my side

**Pull request merged**
